# Generated by Django 4.2.11 on 2024-03-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_itemweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isInside',
            field=models.BooleanField(default=False),
        ),
    ]
